#!/usr/bin/env python3
 
import colors as c
import json
from time import sleep as s

studentdata = open("studentdata.json","r+")
grades = json.load(studentdata)
print(c.clear + c.red + "Grade levels:" + c.x)
for x,y in grades.items():
    print(x + " --> " + str(y))

def find_class():
    grade = input(c.x + "Please enter a grade level\n>> " + c.blue)
    if grade in grades:
        print(c.x + "\nClass list:" + c.blue)
        for listitem in grades[grade]:
            print(str(listitem))
        classroom = input(c.x + "\nPlease enter a class\n>> " + c.blue).title()
        if classroom in grades[grade]:
            print(c.x + "\nStudents:")
            for student in grades[grade][classroom]:
                if grades[grade][classroom][student] == 'present':
                    pcolor = c.green
                elif grades[grade][classroom][student] == 'absent':
                    pcolor = c.red
                else:
                    pcolor = c.B03
                print(c.blue + str(student) + " " + pcolor.rjust(30 - len(student)) + grades[grade][classroom][student] + c.x)
            print()
        else:
            print(c.red + "That class either does not exist or is not documented." + c.x)
    else:
        print(c.red + "That grade level is not documented." + c.x)

def find_student():
    student = input(c.x + "What is the student's name?\n>> " + c.blue).title()
    for grade in grades:
        for classroom in grades[grade]:
            if student in grades[grade][classroom]:
                print(c.x + student + " is in " + grade + "th grade " + classroom + " and they are " + grades[grade][classroom][student])
                exit()
    else:
        print(c.red + "ERROR: STUDENT NOT FOUND")

def start():
    decision = input(c.clear + "Do you wish to see a class list or find a student (c/s)?\n>> " + c.blue).lower()
    if decision == "c":
        find_class()
    elif decision == "s":
        find_student()
    else:
        print(c.x + "That is not an acceptable input")
        s(1.5)
        start()

if __name__ == '__main__':
    try:
        start()
    except KeyboardInterrupt:
        exit()
    except EOFError:
        exit()
