#!/usr/bin/env python3
 
import json
from time import sleep as s

studentdata = open("studentdata.json","r+")
grades = json.load(studentdata)
print("Grade levels:")
for x,y in sorted(grades.items()):
    print(x + " --> " + str(y))

def find_class():
    grade = input("Please enter a grade level\n>> ")
    if grade in grades:
        print("\nClass list:")
        for listitem in grades[grade]:
            print(str(listitem))
        classroom = input("\nPlease enter a class\n>> ").title()
        if classroom in grades[grade]:
            print("\nStudents:")
            for student in grades[grade][classroom]:
                print(str(student) + " " + grades[grade][classroom][student].rjust(30 - len(student)))
            print()
        else:
            print("That class either does not exist or is not documented.")
    else:
        print("That grade level is not documented.")

def find_student():
    student = input("What is the student's name?\n>> ").title()
    for grade in grades:
        for classroom in grades[grade]:
            if student in grades[grade][classroom]:
                print(student + " is in " + grade + "th grade " + classroom + " and they are " + grades[grade][classroom][student])
                exit()
    else:
        print("ERROR: STUDENT NOT FOUND")

def start():
    decision = input("Do you wish to see a class list or find a student (c/s)?\n>> ").lower()
    if decision == "c":
        find_class()
    elif decision == "s":
        find_student()
    else:
        print("That is not an acceptable input")
        s(1.5)
        start()

if __name__ == '__main__':
    try:
        start()
    except KeyboardInterrupt:
        exit()
    except EOFError:
        exit()
