#!/usr/bin/env python3

import barcode
from os import system as s

username = input("What is your name?\n>> ")

c39 = barcode.get('code39', username)

print(c39.get_fullcode())

options = dict(add_checksum = False)

c39.save('c39', options)

s('open -a "Google Chrome" c39.svg')
