#!/usr/bin/env python3
 
import skilstak.colors as c
from urllib.request import urlopen
from os import system

def studentinput():
    student = input("What student would you like to get a QR for?\n").replace(" ","%20")
    if student == " ":
        print("That is not an acceptable student")
        exit()
    return student

def getphoto(student):
    url = 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=' + student + '&qzone=1&bgcolor=194f8d&color=ccc'
    with urlopen(url) as web:
        #returns the encoded image byte
        data = web.read()
        with open('qrphoto.png','wb') as photo:
            photo.write(data)
            system('open -a "Preview" qrphoto.png')

getphoto(studentinput())
